const states = [
  { value: "AL", label: "Alabama", icon: "city" },
  { value: "AK", label: "Alaska", icon: "whale" },
  { value: "AZ", label: "Arizona", icon: "cactus" },
  { value: "AR", label: "Arkansas", icon: "city" },
  { value: "CA", label: "California", icon: "island" },
  { value: "CO", label: "Colorado", icon: "rocky-mountains" },
  { value: "CT", label: "Connecticut", icon: "city" },
  { value: "DE", label: "Delaware", icon: "city" },
  { value: "FL", label: "Florida", icon: "sun" },
  { value: "GA", label: "Georgia", icon: "city" },
  { value: "HI", label: "Hawaii", icon: "island" },
  { value: "ID", label: "Idaho", icon: "rocky-mountains" },
  { value: "IL", label: "Illinois", icon: "city" },
  { value: "IN", label: "Indiana", icon: "city" },
  { value: "IA", label: "Iowa", icon: "city" },
  { value: "KS", label: "Kansas", icon: "sun" },
  { value: "KY", label: "Kentucky", icon: "rocky-mountains" },
  { value: "LA", label: "Louisiana", icon: "sun" },
  { value: "ME", label: "Maine", icon: "city" },
  { value: "MD", label: "Maryland", icon: "city" },
  { value: "MA", label: "Massachusetts", icon: "city" },
  { value: "MI", label: "Michigan", icon: "city" },
  { value: "MN", label: "Minnesota", icon: "pine-tree" },
  { value: "MS", label: "Mississippi", icon: "sun" },
  { value: "MO", label: "Missouri", icon: "city" },
  { value: "MT", label: "Montana", icon: "rocky-mountains" },
  { value: "NE", label: "Nebraska", icon: "city" },
  { value: "NV", label: "Nevada", icon: "cactus" },
  { value: "NH", label: "New Hampshire", icon: "city" },
  { value: "NJ", label: "New Jersey", icon: "city" },
  { value: "NM", label: "New Mexico", icon: "cactus" },
  { value: "NY", label: "New York", icon: "city" },
  { value: "NC", label: "North Carolina", icon: "sun" },
  { value: "ND", label: "North Dakota", icon: "city" },
  { value: "OH", label: "Ohio", icon: "city" },
  { value: "OK", label: "Oklahoma", icon: "sun" },
  { value: "OR", label: "Oregon", icon: "pine-tree" },
  { value: "PA", label: "Pennsylvania", icon: "city" },
  { value: "RI", label: "Rhode Island", icon: "city" },
  { value: "SC", label: "South Carolina", icon: "sun" },
  { value: "SD", label: "South Dakota", icon: "cactus" },
  { value: "TN", label: "Tennessee", icon: "sun" },
  { value: "TX", label: "Texas", icon: "bison" },
  { value: "UT", label: "Utah", icon: "cactus" },
  { value: "VT", label: "Vermont", icon: "city" },
  { value: "VA", label: "Virginia", icon: "city" },
  { value: "WA", label: "Washington", icon: "pine-tree" },
  { value: "WV", label: "West Virginia", icon: "city" },
  { value: "WI", label: "Wisconsin", icon: "city" },
  { value: "WY", label: "Wyoming", icon: "rocky-mountains" },
];

const stateAbbreviations = {
  AL: "Alabama",
  AK: "Alaska",
  AZ: "Arizona",
  AR: "Arkansas",
  CA: "California",
  CO: "Colorado",
  CT: "Connecticut",
  DE: "Delaware",
  FL: "Florida",
  GA: "Georgia",
  HI: "Hawaii",
  ID: "Idaho",
  IL: "Illinois",
  IN: "Indiana",
  IA: "Iowa",
  KS: "Kansas",
  KY: "Kentucky",
  LA: "Louisiana",
  ME: "Maine",
  MD: "Maryland",
  MA: "Massachusetts",
  MI: "Michigan",
  MN: "Minnesota",
  MS: "Mississippi",
  MO: "Missouri",
  MT: "Montana",
  NE: "Nebraska",
  NV: "Nevada",
  NH: "New Hampshire",
  NJ: "New Jersey",
  NM: "New Mexico",
  NY: "New York",
  NC: "North Carolina",
  ND: "North Dakota",
  OH: "Ohio",
  OK: "Oklahoma",
  OR: "Oregon",
  PA: "Pennsylvania",
  RI: "Rhode Island",
  SC: "South Carolina",
  SD: "South Dakota",
  TN: "Tennessee",
  TX: "Texas",
  UT: "Utah",
  VT: "Vermont",
  VA: "Virginia",
  WA: "Washington",
  WV: "West Virginia",
  WI: "Wisconsin",
  WY: "Wyoming",
};

export { states, stateAbbreviations };
